Update GitHub Actions workflow for Termux environment

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -15,26 +15,69 @@ jobs:
     runs-on: ubuntu-24.04-arm
     container:
       image: termux/termux-docker:aarch64
+      volumes: 
+        - /tmp/node20:/__e/node20
+      options: --privileged
 
+    
     env:
+      TERMUX_MAIN_PACKAGE_FORMAT: debian
+      ANDROID_ROOT: /system
+      ANDROID_DATA: /data
+      PREFIX: /data/data/com.termux/files/usr
+      HOME: /data/data/com.termux/files/home
+      PATH: /data/data/com.termux/files/usr/bin
+      TMPDIR: /data/data/com.termux/files/usr/tmp
+      LANG: en_US.UTF-8
+      TZ: UTC
       CARGO_INSTALL_ROOT: /usr/home/cargo
 
     # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
+    
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-
-      # Runs a single command using the runners shell
-      - name: Install
+    steps:
+      - name: set pid_max to 65535
+        run: /entrypoint_root.sh sh -c "echo 65535 | tee /proc/sys/kernel/pid_max"
+      - name: check pid_max is 65535
         run: |
-          pkg upgrade
-          pkg install rust git
+          if [ "$(cat /proc/sys/kernel/pid_max)" -eq 65535 ]; then
+            echo "Successfully changed /proc/sys/kernel/pid_max for container namespace"
+          else
+            echo "Failed to change /proc/sys/kernel/pid_max for container namespace"
+            exit 1
+          fi
+      - name: set pkg command to use the packages-cf.termux.dev mirror
+        run: ln -sf ${PREFIX}/etc/termux/mirrors/default ${PREFIX}/etc/termux/chosen_mirrors
+      - name: upgrade all packages to prepare for installing nodejs
+        run: /entrypoint.sh bash -c "yes | pkg upgrade -y"
+      # actions/checkout will "think" that termux's tar binary isn't executable if it doesn't have
+      # executable bit actually set for all users, since even though that permissions restriction
+      # doesn't actually apply to the root user (at least on Android), GitHub Actions' internal
+      # source code doesn't "care" and would refuse to run the binary anyway.
+      # relevant internal source code of GitHub Actions:
+      # https://github.com/actions/toolkit/blob/930c89072712a3aac52d74b23338f00bb0cfcb24/packages/io/src/io-util.ts#L167-L177
+      - name: fix executable bit for all binaries in $PREFIX/bin for all users
+        run: chmod -R o+x ${PREFIX}/bin
+      - name: install bionic-libc nodejs to force compatibility with actions/checkout and actions/upload-artifact
+        run: |
+          /entrypoint.sh pkg install -y nodejs-lts
+          ln -sf ${PREFIX}/bin /__e/node20/bin
+      - uses: actions/checkout@v4.2.2
+      - name: fix permissions of repository after actions/checkout, which ran as root user, while entrypoint.sh activates system user (1000)
+        run: chown -R 1000:1000 .
+      - name: setup
+        run: |
+          # pkg/pip need to be prefixed with /entrypoint.sh because GHA overrode
+          # the entrypoint.
+          /entrypoint.sh pkg install -y ninja clang python git rust
+          /entrypoint.sh pip install meson
+      - name: build
+        run: |
           git clone https://github.com/mattwparas/helix/
           cd helix
           git checkout steel-event-system
           cargo xtask stell
-
-      # Runs a set of commands using the runners shell
-      - name: Upload
-        uses: actions/upload-artifact@v4
+      - uses: actions/upload-artifact@v4.6.0
         with:
+          name: artifact-${{ matrix.architecture }}
           path: ${{ env.CARGO_INSTALL_ROOT }}
